-- Stone WMS core schema. PostgreSQL-first, Flyway-compatible.
CREATE TABLE warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouse_zone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    zone_type VARCHAR(32) NOT NULL DEFAULT 'STORAGE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_warehouse_zone UNIQUE (warehouse_id, code)
);

CREATE TABLE warehouse_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
    zone_id BIGINT REFERENCES warehouse_zone(id),
    code VARCHAR(64) NOT NULL,
    location_type VARCHAR(32) NOT NULL DEFAULT 'PICKING',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_warehouse_location UNIQUE (warehouse_id, code)
);

CREATE TABLE sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(256) NOT NULL,
    uom VARCHAR(32) NOT NULL DEFAULT 'EA',
    barcode VARCHAR(128),
    shelf_life_days INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory_balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
    sku_id BIGINT NOT NULL REFERENCES sku(id),
    location_id BIGINT NOT NULL REFERENCES warehouse_location(id),
    lot_no VARCHAR(128) NOT NULL DEFAULT '',
    inventory_status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    quantity INTEGER NOT NULL DEFAULT 0,
    allocated_quantity INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_inventory_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT ck_inventory_allocated_non_negative CHECK (allocated_quantity >= 0),
    CONSTRAINT ck_inventory_allocated_not_greater CHECK (allocated_quantity <= quantity),
    CONSTRAINT uk_inventory_balance UNIQUE (tenant_id, warehouse_id, sku_id, location_id, lot_no, inventory_status)
);

CREATE TABLE stock_movement (
    id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    movement_type VARCHAR(32) NOT NULL,
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
    sku_id BIGINT NOT NULL REFERENCES sku(id),
    location_id BIGINT NOT NULL REFERENCES warehouse_location(id),
    lot_no VARCHAR(128) NOT NULL DEFAULT '',
    quantity INTEGER NOT NULL,
    reference_no VARCHAR(128) NOT NULL,
    reason_code VARCHAR(64),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_stock_movement_quantity_positive CHECK (quantity > 0)
);

CREATE TABLE outbox_event (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NEW',
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP,
    CONSTRAINT ck_outbox_retry_non_negative CHECK (retry_count >= 0)
);
